// Generated by CoffeeScript 1.6.3
(function() {
  var image, jsonml2xml, pickRand, xmlEscape;

  xmlEscape = function(str) {
    return str.replace(/&/g, "&amp;").replace(/</g, "&lt;");
  };

  pickRand = function(arr) {
    return arr[Math.random() * arr.length | 0];
  };

  jsonml2xml = function(jsonml) {
    var key, pos, result, val, _ref;
    if (typeof jsonml === "string") {
      return xmlEscape(jsonml);
    }
    result = "<" + jsonml[0];
    pos = 2;
    if (jsonml[1].constructor === Object) {
      _ref = jsonml[1];
      for (key in _ref) {
        val = _ref[key];
        result += " " + key + "=\"" + val + "\"";
      }
    } else {
      --pos;
      pos = 1;
    }
    if (pos === jsonml.length) {
      return result + ">";
    }
    result += ">";
    while (pos < jsonml.length) {
      result += jsonml2xml(jsonml[pos]);
      ++pos;
    }
    return result + ("</" + jsonml[0] + ">");
  };

  console.log(images);

  image = pickRand(images);

  console.log(image);

  $(function() {
    return ($("body")).append(jsonml2xml([
      "div", ["h1", "When was"], [
        "img", {
          src: image.src,
          width: 300
        }
      ], [
        "div", {
          "class": "creator"
        }, image.creator
      ], [
        "div", {
          "class": "title"
        }, image.title
      ], [
        "div", {
          "class": "year"
        }, image.year
      ]
    ]));
  });

}).call(this);
