// Generated by CoffeeScript 1.6.3
(function() {
  var dist, h, margin, w;

  w = 300;

  h = 600;

  margin = .1;

  dist = function(a, b) {
    var i;
    return ((function() {
      var _i, _len, _ref, _results;
      _ref = [0, a.length - 1];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        _results.push(Math.abs(a[i] - b[i]));
      }
      return _results;
    })()).reduce((function(a, b) {
      return a + b;
    }), 0);
  };

  window.isThatKindOfImage = function(url, callback) {
    var img;
    img = new Image(url);
    img.src = url;
    return img.onload = function() {
      var canvas, ctx, d, dx, dy, imData, scale, sum, vector, x, y, _i, _j, _k, _l, _ref, _ref1, _ref2, _ref3;
      canvas = document.createElement("canvas");
      canvas.width = w;
      canvas.height = h;
      ctx = canvas.getContext("2d");
      ctx.drawImage(img, -w * (1 + margin), -h * margin, w * (1 + margin) * 2, h * (1 + 2 * margin));
      imData = ctx.getImageData(0, 0, w, h);
      vector = [];
      scale = 60;
      for (x = _i = 0, _ref = w - 1; scale > 0 ? _i <= _ref : _i >= _ref; x = _i += scale) {
        for (y = _j = 0, _ref1 = h - 1; scale > 0 ? _j <= _ref1 : _j >= _ref1; y = _j += scale) {
          sum = 0;
          for (dx = _k = 0, _ref2 = scale - 1; 0 <= _ref2 ? _k <= _ref2 : _k >= _ref2; dx = 0 <= _ref2 ? ++_k : --_k) {
            for (dy = _l = 0, _ref3 = scale - 1; 0 <= _ref3 ? _l <= _ref3 : _l >= _ref3; dy = 0 <= _ref3 ? ++_l : --_l) {
              sum += imData.data[((x + dx) + (y + dy) * w) * 4] > 128 ? 1 : 0;
            }
          }
          vector.push(sum);
        }
      }
      d = dist(vector, [3465, 3557, 3600, 3555, 3474, 3419, 3470, 3531, 3600, 3540, 3450, 3324, 3571, 3464, 3215, 3159, 2971, 3330, 3600, 3315, 3600, 3144, 3233, 3325, 3086, 3366, 2816, 3378, 3275, 3600, 3600, 3243, 3548, 3419, 2819, 3378, 2824, 3445, 3575, 3600, 3600, 3600, 3600, 3473, 3212, 3422, 3262, 3556, 3600, 3600]);
      return callback(d > 120, url);
    };
  };

}).call(this);
