// Generated by CoffeeScript 1.6.3
(function() {
  var dist, h, margin, w;

  w = 300;

  h = 600;

  margin = .1;

  dist = function(a, b) {
    var i;
    return ((function() {
      var _i, _len, _ref, _results;
      _ref = [0, a.length - 1];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        _results.push(Math.abs(a[i] - b[i]));
      }
      return _results;
    })()).reduce((function(a, b) {
      return a + b;
    }), 0);
  };

  window.isThatKindOfImage = function(url, callback) {
    var img;
    img = new Image(url);
    img.src = url;
    return img.onload = function() {
      var canvas, ctx, dx, dy, imData, scale, sum, vector, x, y, _i, _j, _k, _l, _ref, _ref1, _ref2, _ref3;
      canvas = document.createElement("canvas");
      canvas.width = w;
      canvas.height = h;
      ctx = canvas.getContext("2d");
      ctx.drawImage(img, -w * (1 + margin), -h * margin, w * (1 + margin) * 2, h * (1 + 2 * margin));
      imData = ctx.getImageData(0, 0, w, h);
      vector = [];
      scale = 60;
      for (x = _i = 0, _ref = w - 1; scale > 0 ? _i <= _ref : _i >= _ref; x = _i += scale) {
        for (y = _j = 0, _ref1 = h - 1; scale > 0 ? _j <= _ref1 : _j >= _ref1; y = _j += scale) {
          sum = 0;
          for (dx = _k = 0, _ref2 = scale - 1; 0 <= _ref2 ? _k <= _ref2 : _k >= _ref2; dx = 0 <= _ref2 ? ++_k : --_k) {
            for (dy = _l = 0, _ref3 = scale - 1; 0 <= _ref3 ? _l <= _ref3 : _l >= _ref3; dy = 0 <= _ref3 ? ++_l : --_l) {
              sum += imData.data[((x + dx) + (y + dy) * w) * 4] > 128 ? 1 : 0;
            }
          }
          vector.push(sum);
        }
      }
      return callback(120 < dist(vector, [3313, 3565, 3600, 3555, 3430, 3424, 3463, 3508, 3600, 3511, 3187, 3357, 3581, 3404, 3099, 3208, 3007, 3354, 3600, 3337, 3566, 3262, 3320, 3290, 3038, 3320, 2949, 3381, 3368, 3560, 3600, 3338, 3561, 3404, 2917, 3298, 2956, 3425, 3580, 3600, 3600, 3600, 3600, 3478, 3262, 3426, 3315, 3554, 3600, 3600]), url);
    };
  };

}).call(this);
